"""02 §3.4 里此前只在文档上、真后端还没有执行体的端点(端到端联调 `.omc/handoffs/e2e-console-agent.md` 第 2 节)。

收录:#24 `GET /device-profiles/templates`、#36 `POST /broadcast/commands`、#51 `POST /messages/export`、
#74 `GET /system/env`、#75 `POST /system/probe`、#78 `POST /system/selftest`、#80 `POST /system/diagnostics`、
#84 `POST /system/wsl-restart`、#85 `GET|POST /system/docker-proxy`、#86/#87 `/system/notice[/ack]`、
#90~#93 `/settings/api-clients`。

**为什么单独一个模块**:`api/app.py` 的 `create_api` 已经很长,而这批端点彼此独立、依赖的横切件(鉴权 / 信封 /
审计 / 幂等)都能靠参数传进来。注册点由 `create_api` 决定 —— 必须排在 `/settings/{group}` 兜底路由**之前**
(FastAPI 按注册顺序匹配,否则 `/settings/api-clients` 会被 `{group}` 吃掉)。

🔴 **外部副作用一律经可注入后端**:WinAgent 客户端(`agent.winagent`)、四级探测器(`agent.net_probe`)、
docker 代理执行体(`agent.docker_proxy`)。**本模块不直接执行任何 `wsl` / `systemctl` 命令**
(基线 §11.6 [NOSHUTDOWN]:WSL 重启只能经 WinAgent 发请求)。缺执行体时**诚实回 503 + 明确 reason**,不假装做过。
"""
from __future__ import annotations

import asyncio
import csv
import io
import json
import logging
import os
import zipfile
from typing import Any, Optional

from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse

from .. import device_profiles
from ..events import iso8601
from ..ids import ulid
from ..models import Command, CommandOrigin
from .auth import ApiError, Principal, is_unauth_health_source, require_account, require_level
from .routes_ext2 import note_broadcast
from .serialize import message_view, result_view

log = logging.getLogger("qtrade.api.ext")

#: #86 合规告知的随包默认文案(01-P3);`settings['compliance.notice']` 有值时以库为准
DEFAULT_NOTICE_VERSION = "1"
DEFAULT_NOTICE_TEXT = (
    "本软件在本机托管企点 / QQ / 微信账号并代为收发消息:\n"
    "1. 会替换本机 WSL 内核、写入 hosts 屏蔽行与防火墙规则,三处改动均可逆、卸载时还原;\n"
    "2. 微信侧使用第三方读取组件,存在账号风控风险,请确认已获所属机构许可;\n"
    "3. 企点手机端名额有限,新增账号前请先确认额度;\n"
    "4. 消息正文只落本机数据库,不上传任何云端。\n"
    "勾选即表示你已知晓并同意由本软件执行上述操作。"
)

#: #80 诊断包**不含**项(docs/03 §5.3 逐字:vault、任何密码、微信数据、消息正文;截图默认不带)
DIAG_EXCLUDED = ("vault", "secrets", "wechat_data", "message_text", "screenshots")
#: 日志文件名里命中这些片段的一律不进包(与上面的排除清单同源)
DIAG_SKIP_NAME_PARTS = ("vault", "secret", "token", "password", "wechat")

MESSAGES_EXPORT_FMTS = ("jsonl", "csv", "eml")
MESSAGES_EXPORT_IMPLEMENTED = ("jsonl", "csv")
EXPORT_PAGE = 500                     # 导出作业每轮取多少行(避免一次把全库读进内存)
PROBE_SAMPLE_MAX_S = 30               # 04 §2.8.4:`duration_s` 上限 30
PROBE_LEVELS = ("dns", "tcp", "tls", "http")


class LevelProbe:
    """04 §2.8「逐级探测」的 Agent 侧(WSL/容器侧)执行体协议:``dns → tcp → tls → http``,记录到达的最深一级。

    🔴 **缺省不出网**:`create_api` 只在 ``agent.net_probe`` 被显式注入时才走 WSL 侧探测,否则该侧整体记
    ``SKIPPED(agent_probe_disabled)``(04 §3.4 (df):这一路本期没有默认实现,**不假装探过**)。
    Fake 只要实现 ``async probe(target, timeout_s) -> dict`` 即可编程。
    """

    async def probe(self, target: str, *, timeout_s: float = 5.0) -> dict[str, Any]:   # pragma: no cover - 协议声明
        raise NotImplementedError


def _iso(ms: Optional[int]) -> Optional[str]:
    return iso8601(ms) if ms is not None else None


def _read_text(path: str) -> Optional[str]:
    try:
        with open(path, encoding="utf-8", errors="replace") as f:
            return f.read()
    except OSError:
        return None


class LinuxWslEnvReader:
    """#74 的 WSL 侧快照来源(只读 ``/proc`` / ``/sys`` / ``/etc``);读不到的项一律 ``None``,**不编造**。"""

    def __init__(self, *, proc: str = "/proc", sys: str = "/sys", etc: str = "/etc"):
        self.proc, self.sys, self.etc = proc, sys, etc

    def _default_iface(self) -> Optional[str]:
        raw = _read_text(os.path.join(self.proc, "net", "route"))
        if not raw:
            return None
        for line in raw.splitlines()[1:]:
            cols = line.split()
            if len(cols) >= 2 and cols[1] == "00000000":
                return cols[0]
        return None

    def snapshot(self) -> dict[str, Any]:
        iface = self._default_iface()
        mtu_raw = _read_text(os.path.join(self.sys, "class", "net", iface, "mtu")) if iface else None
        resolv = _read_text(os.path.join(self.etc, "resolv.conf"))
        nameservers = [ln.split()[1] for ln in (resolv or "").splitlines() if ln.startswith("nameserver") and len(ln.split()) > 1]
        generated = resolv is not None and "generated by WSL" in resolv
        pools: Optional[list[Any]] = None
        daemon = _read_text(os.path.join(self.etc, "docker", "daemon.json"))
        if daemon:
            try:
                pools = json.loads(daemon).get("default-address-pools")
            except ValueError:
                pools = None
        ksm_raw = _read_text(os.path.join(self.sys, "kernel", "mm", "ksm", "run"))
        zram_raw = _read_text(os.path.join(self.sys, "block", "zram0", "disksize"))
        return {
            "iface": iface,
            "mtu": int(mtu_raw.strip()) if (mtu_raw or "").strip().isdigit() else None,
            "resolv_conf": {"source": ("wsl_generated" if generated else "custom") if resolv is not None else None,
                            "nameservers": nameservers},
            "docker": {"default_address_pools": pools},
            "ksm": {"run": int(ksm_raw.strip()) if (ksm_raw or "").strip().isdigit() else None},
            "zram": {"disksize_mb": int(zram_raw.strip()) // 1048576 if (zram_raw or "").strip().isdigit() else None},
            "kernel_release": (_read_text(os.path.join(self.proc, "sys", "kernel", "osrelease")) or "").strip() or None,
        }


def register_ext(app: FastAPI, *, agent, cfg, prefix: str, principal, json_or_empty, caps_by_op) -> None:
    """把本模块的端点挂到 ``app``。

    ``principal(request, level)`` / ``json_or_empty(request)`` / ``caps_by_op`` 由 ``create_api`` 传入,
    保证鉴权、错误信封、审计、幂等走的都是**既有那一套**,本模块不另起炉灶。
    """
    P = prefix

    def _audit(p: Principal, action: str, *, result_code: str = "OK", detail: Optional[dict[str, Any]] = None,
               account_id: Optional[str] = None) -> None:
        try:
            agent.store.insert_audit(kind="api", transport=p.transport, actor=p.actor, action=action,
                                     account_id=account_id, result_code=result_code, detail=detail or {}, now_ms=agent.clock())
        except Exception as e:      # 审计失败不影响业务(与 create_api 的 middleware 同口径)
            log.warning("审计写入失败 action=%s: %s", action, e)

    async def _wa(method: str, path: str, *, json_body: Optional[dict[str, Any]] = None, timeout_s: float = 5.0,
                  missing_reason: Optional[str] = None, missing_hint: str = "") -> Optional[dict[str, Any]]:
        """转发到 WinAgent;``404`` 与「不可达 / 其它错」分成不同 reason(与 #76 的 `_wa_probes` 同口径)。"""
        try:
            status, body = await agent.winagent.request(method, path, json=json_body, timeout_s=timeout_s, retry=(method == "GET"))
        except Exception as e:
            raise ApiError(503, "NOT_READY", f"WinAgent 不可达:{e}", reason="winagent_offline", retryable=True)
        if status == 404 and missing_reason:
            raise ApiError(503, "NOT_READY", f"WinAgent 尚未提供该端点({missing_hint})", reason=missing_reason,
                           retryable=False, needs_human=True)
        if status >= 400:
            raise ApiError(503, "NOT_READY", f"WinAgent 回 {status}", reason="winagent_error", retryable=True)
        return body

    # ================================================================== #24 机型档案库模板
    @app.get(f"{P}/device-profiles/templates")
    async def device_profile_templates(request: Request):
        """#24,级别 R:机型档案库模板列表 ``[{profile_key, brand, model, release, weight}]``(C-40;字段名统一 ``profile_key``)。

        数据源 = ``agent.device_profiles``(装配时按 ``[device_profiles] library`` 从随包 JSON 加载,05 §2.5.1);
        没装配 ⇒ 退到 ``device_profiles`` 的内置回落清单(**不读盘**)。
        """
        principal(request, "read")
        return {"ok": True, "data": device_profiles.templates(getattr(agent, "device_profiles", None))}

    # ================================================================== #74 环境快照
    @app.get(f"{P}/system/env")
    async def system_env(request: Request):
        """#74,级别 R:``P-ENV`` 环境快照 = **WinAgent 侧 `GET /wa/v1/net` + WSL 侧只读采集**合并(C-32/04 §3.4)。

        WinAgent 不可达时 ``windows`` 为 ``null`` 且 ``windows_error`` 写明原因(**不假装拿到了机器级信息**);
        WSL 侧读不到的项同样 ``null``。``wslconfig`` 的「生效对比」来自 WinAgent ``GET /wa/v1/wsl/config``,
        同样不可达即 ``null``。
        """
        principal(request, "read")
        reader = getattr(agent, "wsl_env_reader", None) or LinuxWslEnvReader()
        wsl = await asyncio.to_thread(reader.snapshot)
        windows: Optional[dict[str, Any]] = None
        windows_error: Optional[str] = None
        wslconfig: Optional[dict[str, Any]] = None
        try:
            windows = await _wa("GET", "/wa/v1/net")
        except ApiError as e:
            windows_error = e.reason or "winagent_error"
        try:
            wslconfig = await _wa("GET", "/wa/v1/wsl/config", missing_reason="wa_wsl_config_endpoint_missing",
                                  missing_hint="需补 GET /wa/v1/wsl/config")
        except ApiError:
            wslconfig = None
        wsl = dict(wsl)
        wsl["clock"] = {"drift_ms": getattr(agent.timesync, "drift_ms", None),
                        "last_probe_at": _iso(getattr(agent.timesync, "last_probe_ms", None))}
        wsl["adb_server"] = {"running": None, "reason": "no_probe"}      # 本期没有 adb server 探活执行体,不编造
        return {"ok": True, "windows": windows, "windows_error": windows_error, "wsl": wsl,
                "wslconfig": wslconfig, "reboot_required": (windows or {}).get("reboot_required"),
                "winagent": {"online": agent.health.winagent_online, "version": agent.health.winagent_version,
                             "user_agent": agent.health.user_agent_online}}

    # ================================================================== #75 探测(full / sample 两路)
    async def _probe_full(targets: list[str], *, trigger: str, detail: str) -> dict[str, Any]:
        """全量/指定目标探测:Windows 侧转 ``POST /wa/v1/probe``,WSL 侧走可注入的四级探测器。

        WSL 侧没有探测器(缺省)⇒ 该侧每个目标记 ``SKIPPED(agent_probe_disabled)``(04 §3.4 (df) 的开放项,
        **诚实记录,不假装探过**)。WSL 侧的结论经 ``PUT /wa/v1/probes`` 回写(真值只在 winagent.db)。
        """
        run_id = ulid(agent.clock())
        results: list[dict[str, Any]] = []
        try:
            wa_body = await _wa("POST", "/wa/v1/probe", json_body={"targets": targets or None, "trigger": trigger,
                                                                   "detail": detail, "run_id": run_id}, timeout_s=60.0)
            for row in (wa_body or {}).get("results") or []:
                results.append({**row, "side": row.get("side") or "windows"})
        except ApiError as e:
            results.append({"side": "windows", "target": None, "status": "SKIPPED", "level_reached": "none",
                            "detail": e.reason or "winagent_error"})
        probe: Optional[LevelProbe] = getattr(agent, "net_probe", None)
        wsl_rows: list[dict[str, Any]] = []
        for t in targets:
            if probe is None:
                wsl_rows.append({"side": "wsl", "target": t, "status": "SKIPPED", "level_reached": "none",
                                 "detail": "agent_probe_disabled"})
                continue
            try:
                out = await probe.probe(t, timeout_s=5.0)
            except Exception as e:
                out = {"status": "FAIL", "level_reached": "none", "detail": repr(e)[:200]}
            wsl_rows.append({"side": "wsl", "target": t, "run_id": run_id, **out})
        results += wsl_rows
        if wsl_rows and probe is not None:
            try:
                await _wa("PUT", "/wa/v1/probes", json_body={"run_id": run_id, "results": wsl_rows})
            except ApiError as e:
                log.warning("#75 WSL 侧结果回写失败(%s):结果照常同步返回,库里没有这一份", e.reason)
        return {"run_id": run_id, "results": results}

    @app.post(f"{P}/system/probe")
    async def system_probe(request: Request):
        """#75,级别 W。``mode`` 缺省 ``"probe"``(= 全量/指定目标四级探测,同步返回 ``{run_id, results}``);
        ``mode:"sample"``(C-1,04 §2.8.4)= 实测采样,返回逐字 ``{sampled_at, duration_s, rows, skipped}`` —— **没有 `run_id`**
        (sample 不产生 `probe_result`)。``mode:"full"`` 是 ``"probe"`` 的同义词(04 §3.4 用这个写法)。
        """
        p = principal(request, "write")
        body = await json_or_empty(request)
        mode = body.get("mode") or "probe"
        if mode not in ("probe", "full", "sample"):
            raise ApiError(400, "INVALID_ARGS", "mode 须为 probe|full|sample", reason="bad_mode",
                           extra={"details": [{"pointer": "/mode"}]})
        if mode == "sample":
            raw = body.get("duration_s", 10)
            try:
                duration = float(raw)
            except (TypeError, ValueError):
                raise ApiError(400, "INVALID_ARGS", "duration_s 须为数字", reason="bad_duration",
                               extra={"details": [{"pointer": "/duration_s"}]})
            if not (0 < duration <= PROBE_SAMPLE_MAX_S):
                raise ApiError(400, "INVALID_ARGS", f"duration_s 须在 (0, {PROBE_SAMPLE_MAX_S}]", reason="bad_duration",
                               extra={"details": [{"pointer": "/duration_s"}]})
            out = await agent.sample_observed(duration_s=duration)
            running = {r["channel"] for r in agent.store.list_accounts(state="running")}
            skipped = [{"channel": ch, "account_id": None, "reason": "no_running_account"}
                       for ch in ("qidian", "qq", "wechat") if ch not in running]
            _audit(p, "system.probe", detail={"mode": "sample", "duration_s": duration, "rows": len(out.get("rows") or [])})
            return {"ok": True, "sampled_at": out.get("sampled_at"), "duration_s": out.get("duration_s"),
                    "rows": out.get("rows") or [], "skipped": skipped}
        targets = body.get("targets") or []
        if not isinstance(targets, list) or any(not isinstance(t, str) or not t for t in targets):
            raise ApiError(400, "INVALID_ARGS", "targets 须为非空字符串数组(缺省 = 全量)", reason="bad_targets",
                           extra={"details": [{"pointer": "/targets"}]})
        trigger = body.get("trigger") or "manual"
        if trigger not in ("manual", "wizard", "install"):
            raise ApiError(400, "INVALID_ARGS", "trigger 须为 manual|wizard|install", reason="bad_trigger",
                           extra={"details": [{"pointer": "/trigger"}]})
        out = await _probe_full(list(targets), trigger=trigger, detail=str(body.get("detail") or ""))
        _audit(p, "system.probe", detail={"mode": mode, "trigger": trigger, "targets": targets, "run_id": out["run_id"]})
        return {"ok": True, **out}

    # ================================================================== #78 自检
    @app.post(f"{P}/system/selftest")
    async def system_selftest_run(request: Request):
        """#78,级别 A → ``202 {run_id}``;结果经 #79 ``GET /system/selftest/{run_id}`` 取(02 逐字给的就是 `run_id`,
        **不是 `job_id`** —— `jobs.kind` 的 CHECK 里没有 selftest,硬塞会直接违反约束)。

        ⚠️ **临时 redroid(adb 16099)那一步本期没有执行体** ⇒ ``redroid_boot_ms`` / ``napcat_ok`` 如实回 ``null``
        并在 ``skipped`` 里写明原因,不假装启过容器(04 §2.4.5 的「不编造」同口径)。
        """
        p = principal(request, "admin")
        body = await json_or_empty(request)
        run_id = ulid(agent.clock())
        targets = body.get("targets") or []
        if not isinstance(targets, list):
            raise ApiError(400, "INVALID_ARGS", "targets 须为数组", reason="bad_targets",
                           extra={"details": [{"pointer": "/targets"}]})

        async def body_fn() -> None:
            started = agent.clock()
            try:
                ping = await agent.winagent.ping()
            except Exception:
                ping = None
            try:
                probes = (await _probe_full(list(targets), trigger="install", detail="selftest"))["results"]
            except ApiError as e:
                probes = [{"side": "windows", "status": "SKIPPED", "level_reached": "none", "detail": e.reason or "probe_failed"}]
            data = {"run_id": run_id, "redroid_boot_ms": None, "napcat_ok": None,
                    "winagent_ok": ping is not None, "winagent_version": (ping or {}).get("version"),
                    "probes": probes, "started_at": _iso(started), "finished_at": _iso(agent.clock()),
                    "skipped": [{"step": "redroid_boot", "reason": "no_executor"},
                                {"step": "napcat", "reason": "no_executor"}]}
            agent.store.settings_set(f"system.selftest.{run_id}", data, actor=p.actor)
            agent.store.settings_set("system.selftest.last", run_id, actor=p.actor)
            agent.events.emit("job", payload={"job_id": run_id, "kind": "selftest", "state": "succeeded"})

        asyncio.create_task(body_fn(), name=f"selftest:{run_id}")
        _audit(p, "system.selftest", detail={"run_id": run_id})
        return JSONResponse(status_code=202, content={"ok": True, "run_id": run_id})

    # ================================================================== #80 诊断包
    def _diag_pack(job_id: str, payload: dict[str, Any], log_dir: str, out_path: str) -> dict[str, Any]:
        os.makedirs(os.path.dirname(out_path), exist_ok=True)
        included: list[str] = []
        with zipfile.ZipFile(out_path, "w", compression=zipfile.ZIP_DEFLATED) as z:
            for name, blob in payload.items():
                z.writestr(f"{name}.json", json.dumps(blob, ensure_ascii=False, indent=2, default=str))
                included.append(f"{name}.json")
            if os.path.isdir(log_dir):
                for fn in sorted(os.listdir(log_dir)):
                    low = fn.lower()
                    if any(part in low for part in DIAG_SKIP_NAME_PARTS):
                        continue                                  # docs/03 §5.3:vault / 密码 / 微信数据一律不进包
                    src = os.path.join(log_dir, fn)
                    if os.path.isfile(src):
                        z.write(src, f"logs/{fn}")
                        included.append(f"logs/{fn}")
        return {"file_path": out_path, "bytes": os.path.getsize(out_path), "included": included,
                "excluded": list(DIAG_EXCLUDED)}

    @app.post(f"{P}/system/diagnostics")
    async def system_diagnostics(request: Request):
        """#80,级别 A:``{since?, until?, with_screenshots:false}`` → ``202 {job_id}``(``jobs.kind='diagnostics'``);
        产物路径经 #107 ``GET /jobs/{job_id}`` 的 ``result.file_path`` 取。

        包内含 ``env``(#74)/``health``/``alerts``/``schema_version``/日志;**不含** vault、任何密码、微信数据、
        消息正文(docs/03 §5.3 逐字),排除清单原样回在 ``result.excluded`` 里。``with_screenshots`` 本期只接受 ``false``。
        """
        p = principal(request, "admin")
        body = await json_or_empty(request)
        if body.get("with_screenshots"):
            raise ApiError(400, "INVALID_ARGS", "with_screenshots 本期只接受 false(截图执行体未实现)",
                           reason="screenshots_not_implemented", extra={"details": [{"pointer": "/with_screenshots"}]})
        job_id = agent.store.job_create(kind="diagnostics", actor=p.actor,
                                        params={"since": body.get("since"), "until": body.get("until"),
                                                "with_screenshots": False})

        async def job_body() -> dict[str, Any]:
            env: Any
            try:
                env = await system_env(request)
            except ApiError as e:
                env = {"error": e.reason or e.code}
            payload = {
                "env": env,
                "health": {"winagent": agent.health.winagent_online, "dockerd": agent.health.dockerd_ok,
                           "uptime_s": agent.health.uptime_s(), "checks": agent.healthloop.checks()},
                "alerts": [{"code": a.code, "subject": a.subject, "severity": a.severity, "count": a.count}
                           for a in agent.alerts.active.values()],
                "schema_version": agent.store.con.execute("SELECT MAX(version) FROM schema_version").fetchone()[0],
                "scheduler": agent.scheduler.snapshot(),
            }
            out_path = os.path.join(agent.data_dir, "exports", f"diag-{job_id}.zip")
            return await asyncio.to_thread(_diag_pack, job_id, payload, os.path.join(agent.data_dir, "logs"), out_path)

        agent.spawn_job(job_id, "diagnostics", job_body)
        _audit(p, "system.diagnostics", detail={"job_id": job_id})
        return JSONResponse(status_code=202, content={"ok": True, "job_id": job_id})

    # ================================================================== #84 WSL 重启(🔴 危险操作)
    @app.post(f"{P}/system/wsl-restart")
    async def system_wsl_restart(request: Request):
        """#84,级别 **A** → ``202 {run_id}``。C-03 ①:控制台 → Agent → **WinAgent**;
        🔴 **本端点只经 WinAgent 客户端发请求,本机一条 `wsl` 命令都不执行**(基线 §11.6 [NOSHUTDOWN])。

        ``mode:'terminate'|'shutdown'``;``shutdown`` **必须带 `confirm:true`**(用户已在控制台确认)。
        受理后先 drain(停掉全部 running 账号,`desired_state` 不动),再调 ``POST /wa/v1/wsl/restart``;
        Agent 随发行版一起停,恢复由会话代理 ``autostart`` 拉起。无论成败都记审计。
        """
        p = principal(request, "admin")
        body = await json_or_empty(request)
        mode = body.get("mode")
        if mode not in ("terminate", "shutdown"):
            raise ApiError(400, "INVALID_ARGS", "mode 须为 terminate|shutdown", reason="bad_mode",
                           extra={"details": [{"pointer": "/mode"}]})
        if mode == "shutdown" and body.get("confirm") is not True:
            _audit(p, "system.wsl_restart", result_code="INVALID_ARGS", detail={"mode": mode, "reason": "confirm_required"})
            raise ApiError(400, "INVALID_ARGS", "mode='shutdown' 必须带 confirm:true(基线 §11.6 [NOSHUTDOWN])",
                           reason="confirm_required", extra={"details": [{"pointer": "/confirm"}]})
        run_id = ulid(agent.clock())
        running = [r["id"] for r in agent.store.list_accounts(state="running")]
        _audit(p, "system.wsl_restart", detail={"run_id": run_id, "mode": mode, "drain": running})

        async def body_fn() -> None:
            for aid in running:
                try:
                    await agent.accounts.stop(aid, graceful=True, actor=p.actor)
                except Exception as e:
                    log.warning("#84 drain 账号 %s 失败(继续):%s", aid, e)
            try:
                await _wa("POST", "/wa/v1/wsl/restart", json_body={"mode": mode, "run_id": run_id}, timeout_s=30.0)
            except ApiError as e:
                log.error("#84 调 WinAgent 重启失败:%s", e.message)
                agent.store.settings_set(f"system.wsl_restart.{run_id}",
                                         {"ok": False, "mode": mode, "reason": e.reason}, actor=p.actor)
                return
            agent.store.settings_set(f"system.wsl_restart.{run_id}", {"ok": True, "mode": mode}, actor=p.actor)

        asyncio.create_task(body_fn(), name=f"wsl-restart:{run_id}")
        return JSONResponse(status_code=202, content={"ok": True, "run_id": run_id, "mode": mode, "drained": running})

    # ================================================================== #85 docker 代理透传
    @app.get(f"{P}/system/docker-proxy")
    async def get_docker_proxy(request: Request):
        """#85 的只读兄弟端点(02 只给了 POST 半;P-ENV 要先能显示当前状态才谈得上开关)。
        回 ``settings['system.docker_proxy']`` 的最后一次落地结果,没开过 ⇒ ``{enabled:false, proxy:null}``。"""
        principal(request, "read")
        st = agent.store.settings_get("system.docker_proxy") or {}
        return {"ok": True, "enabled": bool(st.get("enabled")), "proxy": st.get("proxy"),
                "applied_at": st.get("applied_at"), "applier": getattr(agent, "docker_proxy", None) is not None}

    @app.post(f"{P}/system/docker-proxy")
    async def post_docker_proxy(request: Request):
        """#85,级别 A:``{enable:true}`` → 从 ``GET /wa/v1/net`` 取机器级代理 → 交给**可注入执行体**写
        ``docker.service.d/proxy.conf`` 并重启 docker → ``{applied, proxy}``(C-03 ②)。

        🔴 重启 docker 会连带重启全部容器 ⇒ **有 running 账号且未带 `confirm:true` 时回 `202 {pending:true}`**
        (04 §3.4「零账号或用户确认后才重启 docker」)。执行体未注入 ⇒ ``503 NOT_READY(docker_proxy_applier_missing)``,
        **不假装写过 proxy.conf**。
        """
        p = principal(request, "admin")
        body = await json_or_empty(request)
        enable = body.get("enable")
        if not isinstance(enable, bool):
            raise ApiError(400, "INVALID_ARGS", "enable 须为 true|false", reason="bad_enable",
                           extra={"details": [{"pointer": "/enable"}]})
        running = [r["id"] for r in agent.store.list_accounts(state="running")]
        if running and body.get("confirm") is not True:
            return JSONResponse(status_code=202, content={"ok": True, "pending": True, "reason": "accounts_running",
                                                          "running": running})
        # 先判执行体再去问 WinAgent 要代理:没有执行体时这一趟转发是白跑的,而且回 `winagent_error`
        # 会把现场引到错的方向(真正缺的是本机这一侧的执行体)
        applier = getattr(agent, "docker_proxy", None)
        if applier is None:
            raise ApiError(503, "NOT_READY", "docker 代理执行体未装配(写 proxy.conf + 重启 docker 需显式注入)",
                           reason="docker_proxy_applier_missing", retryable=False, needs_human=True)
        proxy: Optional[dict[str, Any]] = None
        if enable:
            net = await _wa("GET", "/wa/v1/net") or {}
            proxy = (net.get("proxy") or {}).get("winhttp") or net.get("proxy")
            if not proxy:
                raise ApiError(409, "NOT_APPLICABLE", "WinAgent 未报告机器级代理,无可透传的配置", reason="no_machine_proxy")
        applied = bool(await applier.apply(proxy) if enable else await applier.disable())
        now = agent.clock()
        agent.store.settings_set("system.docker_proxy", {"enabled": bool(enable and applied), "proxy": proxy,
                                                         "applied_at": _iso(now)}, actor=p.actor)
        _audit(p, "system.docker_proxy", detail={"enable": enable, "applied": applied})
        return {"ok": True, "applied": applied, "proxy": proxy}

    # ================================================================== #86 / #87 合规告知
    def _notice() -> dict[str, Any]:
        st = agent.store.settings_get("compliance.notice") or {}
        return {"notice_version": str(st.get("notice_version") or DEFAULT_NOTICE_VERSION),
                "text": str(st.get("text") or DEFAULT_NOTICE_TEXT)}

    @app.get(f"{P}/system/notice")
    async def get_notice(request: Request):
        """#86,级别 R(**loopback 免鉴权**:首启还没有令牌时也要能显示告知页,与 #72 同一套来源判定)。"""
        auth = request.headers.get("Authorization", "")
        host = request.client.host if request.client else None
        if auth.lower().startswith("bearer ") or not is_unauth_health_source(host, cfg.api.unauth_health_sources, agent.wsl_gateway):
            principal(request, "read")
        st = agent.store.settings_get("compliance.ack") or {}
        return {"ok": True, **_notice(), "ack_ms": st.get("ack_ms"), "acked_at": _iso(st.get("ack_ms")),
                "acked_version": st.get("notice_version")}

    @app.put(f"{P}/system/notice")
    async def put_notice(request: Request):
        """#86 的写半(02 只给了读半;文案要能随发行版更新,否则「版本升级后需重新勾选」无从触发),级别 **A**。
        ``{notice_version, text}``;换了版本即视为需要重新勾选(#87 会因版本不符而拒)。"""
        p = principal(request, "admin")
        body = await json_or_empty(request)
        version, text = body.get("notice_version"), body.get("text")
        if not isinstance(version, str) or not version.strip():
            raise ApiError(400, "INVALID_ARGS", "notice_version 必填", reason="bad_notice_version",
                           extra={"details": [{"pointer": "/notice_version"}]})
        if not isinstance(text, str) or not text.strip():
            raise ApiError(400, "INVALID_ARGS", "text 必填", reason="bad_text", extra={"details": [{"pointer": "/text"}]})
        agent.store.settings_set("compliance.notice", {"notice_version": version.strip(), "text": text}, actor=p.actor)
        _audit(p, "settings.update", detail={"group": "compliance", "notice_version": version.strip()})
        return {"ok": True, **_notice()}

    @app.post(f"{P}/system/notice/ack")
    async def ack_notice(request: Request):
        """#87,级别 A:``{notice_version}`` → 写 ``settings compliance.ack_ms / compliance.notice_version``。
        版本与当前文案不符 ⇒ ``400``(升级后必须重新勾选的就是这一条)。"""
        p = principal(request, "admin")
        body = await json_or_empty(request)
        cur = _notice()["notice_version"]
        version = body.get("notice_version")
        if not isinstance(version, str) or not version.strip():
            raise ApiError(400, "INVALID_ARGS", "notice_version 必填", reason="bad_notice_version",
                           extra={"details": [{"pointer": "/notice_version"}]})
        if version.strip() != cur:
            raise ApiError(400, "INVALID_ARGS", f"告知文案已更新到 {cur},请重新阅读并勾选", reason="notice_version_stale",
                           extra={"details": [{"pointer": "/notice_version"}], "notice_version": cur})
        now = agent.clock()
        agent.store.settings_set("compliance.ack", {"ack_ms": now, "notice_version": cur}, actor=p.actor)
        _audit(p, "settings.update", detail={"group": "compliance", "op": "ack", "notice_version": cur})
        return {"ok": True, "notice_version": cur, "ack_ms": now, "acked_at": _iso(now)}

    # ================================================================== #90~#93 调用方令牌
    CLIENT_LEVELS = ("read", "write", "admin")
    CLIENT_AUTH_KINDS = ("bearer", "hmac")
    BUILTIN_APP_IDS = ("console",)         # P-15:控制台内置调用方,吊销它等于把自己锁在门外
    #: #92 宽限期登记:**单键 map** `{app_id: {old_hash, until_ms}}`(鉴权侧 `_grace_client` 一次读完,
    #: 不必为查一次宽限去扫 settings 的键前缀)
    GRACE_KEY = "api_clients.grace"

    def _grace_put(app_id: str, blob: Optional[dict[str, Any]], actor: str) -> None:
        grace = agent.store.settings_get(GRACE_KEY) or {}
        if not isinstance(grace, dict):
            grace = {}
        now = agent.clock()
        grace = {k: v for k, v in grace.items()                         # 顺手把过期项清掉,免得越积越多
                 if isinstance(v, dict) and int(v.get("until_ms") or 0) > now and k != app_id}
        if blob is not None:
            grace[app_id] = blob
        agent.store.settings_set(GRACE_KEY, grace, actor=actor)

    def _client_view(row: dict[str, Any]) -> dict[str, Any]:
        """**不含 secret**(连 ``secret_hash`` 都不出表,#90 逐字)。"""
        def _json(col: str, default: Any) -> Any:
            try:
                return json.loads(row.get(col) or json.dumps(default))
            except ValueError:
                return default
        return {"app_id": row["app_id"], "name": row["name"], "auth_kind": row["auth_kind"], "level": row["level"],
                "ip_allow": _json("ip_allow_json", []), "allow_ops": _json("allow_ops_json", ["*"]),
                "allow_accounts": _json("allow_accounts_json", ["*"]), "rate_per_min": row["rate_per_min"],
                "api_version_min": row["api_version_min"], "enabled": bool(row["enabled"]),
                "secret_ref": row.get("secret_ref"), "builtin": row["app_id"] in BUILTIN_APP_IDS,
                "created_at": _iso(row["created_ms"]), "updated_at": _iso(row["updated_ms"]),
                "last_used_at": _iso(row.get("last_used_ms")), "revoked_at": _iso(row.get("revoked_ms"))}

    def _client_or_404(app_id: str) -> dict[str, Any]:
        row = agent.store.api_client_get(app_id)
        if row is None:
            raise ApiError(404, "TARGET_NOT_FOUND", f"调用方不存在:{app_id}")
        return row

    @app.get(f"{P}/settings/api-clients")
    async def list_api_clients(request: Request, include_revoked: bool = False):
        """#90,级别 A:列表(**不含 secret**)。缺省不列已吊销的,``?include_revoked=true`` 才带上。"""
        principal(request, "admin")
        return {"ok": True, "data": [_client_view(r) for r in agent.store.api_clients_list(include_revoked=include_revoked)]}

    @app.post(f"{P}/settings/api-clients", status_code=201)
    async def create_api_client(request: Request):
        """#91,级别 A:``{name, auth_kind?, level, ip_allow?, allow_ops?, allow_accounts?, rate_per_min?, api_version_min?}``
        → **一次性**返回 ``token``(bearer)或 ``secret``(hmac,同时写 Vault ``api/<app_id>`` 并落 ``secret_ref``)。
        库里只留 ``sha256``,**此后再也读不回明文**。"""
        p = principal(request, "admin")
        body = await json_or_empty(request)
        name = body.get("name")
        if not isinstance(name, str) or not name.strip():
            raise ApiError(400, "INVALID_ARGS", "name 必填", reason="bad_name", extra={"details": [{"pointer": "/name"}]})
        level = body.get("level")
        if level not in CLIENT_LEVELS:
            raise ApiError(400, "INVALID_ARGS", f"level 须为 {'|'.join(CLIENT_LEVELS)}", reason="bad_level",
                           extra={"details": [{"pointer": "/level"}]})
        auth_kind = body.get("auth_kind") or "bearer"
        if auth_kind not in CLIENT_AUTH_KINDS:
            raise ApiError(400, "INVALID_ARGS", f"auth_kind 须为 {'|'.join(CLIENT_AUTH_KINDS)}", reason="bad_auth_kind",
                           extra={"details": [{"pointer": "/auth_kind"}]})
        for key in ("ip_allow", "allow_ops", "allow_accounts"):
            v = body.get(key)
            if v is not None and (not isinstance(v, list) or any(not isinstance(x, str) for x in v)):
                raise ApiError(400, "INVALID_ARGS", f"{key} 须为字符串数组", reason=f"bad_{key}",
                               extra={"details": [{"pointer": f"/{key}"}]})
        app_id = body.get("app_id") or f"app-{ulid(agent.clock())[-10:].lower()}"
        if not isinstance(app_id, str) or not app_id.strip():
            raise ApiError(400, "INVALID_ARGS", "app_id 须为非空字符串", reason="bad_app_id",
                           extra={"details": [{"pointer": "/app_id"}]})
        if agent.store.api_client_get(app_id) is not None:
            raise ApiError(400, "INVALID_ARGS", f"app_id 已存在:{app_id}", reason="app_id_taken",
                           extra={"details": [{"pointer": "/app_id"}]})
        secret = ulid() + ulid()
        secret_ref = None
        if auth_kind == "hmac":
            await agent.vault.put(f"api/{app_id}", secret, scope="api")      # HMAC 验签要明文 ⇒ 存 Vault
            secret_ref = f"vault://api/{app_id}"
        row = agent.store.api_client_create(app_id=app_id, name=name.strip(), auth_kind=auth_kind, level=level,
                                            token=secret, ip_allow=body.get("ip_allow"), allow_ops=body.get("allow_ops"),
                                            allow_accounts=body.get("allow_accounts"),
                                            rate_per_min=int(body.get("rate_per_min") or 120),
                                            api_version_min=int(body.get("api_version_min") or 1),
                                            secret_ref=secret_ref, now_ms=agent.clock())
        _audit(p, "settings.update", detail={"group": "api_clients", "op": "create", "app_id": app_id, "level": level})
        # 🔴 形状按 §3.4 R6-55 **单一形状**:#91 的响应列是字面键集(「一次性返回 `token` 或 `secret`」)、
        #    `ApiClient` 不在 00 §7 的对象清单里 ⇒ **顶层平铺 + `ok`**,不包 `data`。
        #    此前「行包 `data`、明文令牌放顶层」两种形状各占一半,客户端「有 data 就返回 data」这一跳会把
        #    **只下发一次**的明文令牌丢掉(独立复测 N-1,P0)。
        out = {"ok": True, **_client_view(row)}
        out["secret" if auth_kind == "hmac" else "token"] = secret            # 一次性下发,不再回读
        return out

    @app.post(f"{P}/settings/api-clients/{{app_id}}/rotate")
    async def rotate_api_client(request: Request, app_id: str):
        """#92,级别 A:轮换,**旧凭据宽限 `grace_minutes`(默认 10)**。

        库里只有一列 ``secret_hash`` ⇒ 旧 hash 与到期时刻落 ``settings['api_clients.grace.<app_id>']``,
        鉴权时由 ``_principal_from_token`` 兜底认一次(过期即失效)。"""
        p = principal(request, "admin")
        row = _client_or_404(app_id)
        if row.get("revoked_ms"):
            raise ApiError(409, "NOT_APPLICABLE", f"调用方已吊销,不能轮换:{app_id}", reason="client_revoked")
        body = await json_or_empty(request)
        grace_minutes = body.get("grace_minutes", 10)
        if not isinstance(grace_minutes, int) or isinstance(grace_minutes, bool) or not (0 <= grace_minutes <= 1440):
            raise ApiError(400, "INVALID_ARGS", "grace_minutes 须为 0~1440 的整数", reason="bad_grace_minutes",
                           extra={"details": [{"pointer": "/grace_minutes"}]})
        secret = ulid() + ulid()
        now = agent.clock()
        old_hash = agent.store.api_client_rotate(app_id, secret, now_ms=now)
        if row["auth_kind"] == "hmac":
            await agent.vault.put(f"api/{app_id}", secret, scope="api")
        _grace_put(app_id, {"old_hash": old_hash, "until_ms": now + grace_minutes * 60_000}
                   if (grace_minutes > 0 and old_hash) else None, p.actor)
        _audit(p, "settings.update", detail={"group": "api_clients", "op": "rotate", "app_id": app_id,
                                             "grace_minutes": grace_minutes})
        # 形状同 #91(R6-55 单一形状:顶层平铺,不包 `data`)—— 轮换回的也是只此一次的明文凭据。
        out = {"ok": True, **_client_view(_client_or_404(app_id)), "grace_minutes": grace_minutes,
               "grace_until": _iso(now + grace_minutes * 60_000) if grace_minutes > 0 else None}
        out["secret" if row["auth_kind"] == "hmac" else "token"] = secret
        return out

    @app.delete(f"{P}/settings/api-clients/{{app_id}}")
    async def revoke_api_client(request: Request, app_id: str):
        """#93,级别 A:吊销(行保留、``enabled=0`` + ``revoked_ms``,审计要能回指)。
        内置 ``console`` 不可吊销 —— 吊了控制台自己就再也连不上(P-15)。"""
        p = principal(request, "admin")
        _client_or_404(app_id)
        if app_id in BUILTIN_APP_IDS:
            raise ApiError(409, "NOT_APPLICABLE", f"内置调用方不可吊销:{app_id}", reason="builtin_readonly")
        revoked = agent.store.api_client_revoke(app_id, now_ms=agent.clock())
        _grace_put(app_id, None, p.actor)                                       # 吊销即刻掐断宽限期
        _audit(p, "settings.update", detail={"group": "api_clients", "op": "revoke", "app_id": app_id})
        return {"ok": True, "revoked": revoked, "app_id": app_id}

    # ================================================================== #36 群发指令
    @app.post(f"{P}/broadcast/commands")
    async def broadcast_commands(request: Request):
        """#36,级别 W:``{account_ids:[…], op, args, idempotency_key, confirm}`` → ``200 {broadcast_id, results:{account_id: CommandResult}}``。

        🔴 **不接受 `"*"`**(02 #36 逐字):群发必须由调用方把账号逐个列出来,免得配置一变就多发给了不该发的人。
        每账号幂等键 = ``key + ':' + account_id``;各账号**并行**提交、各自超时;GATE 与审计照常
        (都在 ``bus.submit`` 里,本端点不绕过)。
        """
        p = principal(request, "write")
        body = await json_or_empty(request)
        ids = body.get("account_ids")
        if not isinstance(ids, list) or not ids or any(not isinstance(x, str) or not x for x in ids):
            raise ApiError(400, "INVALID_ARGS", "account_ids 须为非空字符串数组", reason="bad_account_ids",
                           extra={"details": [{"pointer": "/account_ids"}]})
        if "*" in ids:
            raise ApiError(400, "INVALID_ARGS", "群发不接受 '*',须显式列出账号(02 #36)", reason="wildcard_not_allowed",
                           extra={"details": [{"pointer": "/account_ids"}]})
        if len(set(ids)) != len(ids):
            raise ApiError(400, "INVALID_ARGS", "account_ids 有重复", reason="duplicate_account_ids",
                           extra={"details": [{"pointer": "/account_ids"}]})
        op = body.get("op")
        if not isinstance(op, str) or op not in caps_by_op:
            raise ApiError(400, "INVALID_ARGS", f"未知能力 op={op!r}", reason="unknown_op",
                           extra={"details": [{"pointer": "/op"}]})
        cap = caps_by_op[op]
        key = body.get("idempotency_key")
        if cap["kind"] != "read" and (not isinstance(key, str) or not key or len(key) > 96):
            raise ApiError(400, "INVALID_ARGS", "写类群发必带 idempotency_key(≤96 字符,逐账号再拼 ':<account_id>')",
                           reason="idempotency_key_required", extra={"details": [{"pointer": "/idempotency_key"}]})
        require_level(p, "read" if cap["kind"] == "read" else ("admin" if cap["kind"] == "admin" else "write"))
        confirm = bool(body.get("confirm", True))
        args = body.get("args") or {}
        for aid in ids:
            require_account(p, aid)
            acct = agent.store.get_account(aid)
            if acct is None:
                raise ApiError(404, "TARGET_NOT_FOUND", f"账号不存在:{aid}")
            if acct["channel"] == "wechat" and not confirm:
                raise ApiError(400, "INVALID_ARGS", "微信不支持 confirm:false(C-30)", reason="wechat_confirm_required",
                               extra={"details": [{"pointer": "/confirm"}]})
        broadcast_id = ulid(agent.clock())
        timeout_ms = int(body.get("timeout_ms") or cfg.bus.default_timeout_ms)
        origin = CommandOrigin(transport=p.transport, actor=p.actor, ip=request.client.host if request.client else None)
        cmds = [Command(account_id=aid, op=op, args=args, idempotency_key=(f"{key}:{aid}" if key else None),
                        confirm=confirm, timeout_ms=timeout_ms, origin=origin, trace_id=ulid(),
                        submitted_at_ms=agent.clock()) for aid in ids]
        done = await asyncio.gather(*(agent.bus.submit(c) for c in cmds), return_exceptions=True)
        results: dict[str, Any] = {}
        for aid, res in zip(ids, done):
            if isinstance(res, BaseException):
                log.exception("#36 群发 %s 失败:%s", aid, res)
                results[aid] = {"ok": False, "code": "INTERNAL", "data": {}, "cost_ms": None, "trace_id": None,
                                "source": None, "state_before": None, "state_after": None,
                                "error": {"message": str(res), "reason": "internal", "retryable": True,
                                          "needs_human": False, "details": []}}
            else:
                results[aid] = result_view(res)
        _audit(p, "broadcast.commands", detail={"broadcast_id": broadcast_id, "op": op, "accounts": ids})
        # #37 `GET /broadcast/{broadcast_id}` 要能查回这一次的汇总 ⇒ 落 `settings['broadcast.<id>']`
        # (`jobs.kind` 的 CHECK 里没有 broadcast,硬塞会违反约束;同 #78 自检落 settings 的做法)
        note_broadcast(agent.store, broadcast_id=broadcast_id, op=op, actor=p.actor, results=results,
                       now_ms=agent.clock())
        return {"ok": True, "broadcast_id": broadcast_id, "results": results}

    # ================================================================== #51 消息导出
    def _export_write(job_id: str, fmt: str, rows: list[dict[str, Any]], out_path: str) -> dict[str, Any]:
        os.makedirs(os.path.dirname(out_path), exist_ok=True)
        views = [message_view(r) for r in rows]
        if fmt == "jsonl":
            with open(out_path, "w", encoding="utf-8") as f:
                for v in views:
                    f.write(json.dumps(v, ensure_ascii=False) + "\n")
        else:
            cols = ("id", "ext_msg_id", "account_id", "channel", "dir", "type", "state", "ts", "received_at",
                    "sender", "session", "text", "source", "trace_id")
            buf = io.StringIO()
            w = csv.writer(buf)
            w.writerow(cols)
            for v in views:
                w.writerow([json.dumps(v[c], ensure_ascii=False) if isinstance(v.get(c), (dict, list)) else
                            ("" if v.get(c) is None else v[c]) for c in cols])
            with open(out_path, "w", encoding="utf-8-sig", newline="") as f:
                f.write(buf.getvalue())
        return {"rows": len(views), "bytes": os.path.getsize(out_path), "file_path": out_path}

    @app.post(f"{P}/messages/export")
    async def messages_export(request: Request):
        """#51,级别 R:``{fmt:'jsonl|csv|eml', with_media:'none|zip', filter:{…#48 的过滤}}`` → ``202 {job_id}``
        (``jobs.kind='messages_export'``,§2.8.7);产物路径经 #107 的 ``result.file_path`` 取。

        ⚠️ ``fmt='eml'`` 与 ``with_media='zip'`` 本期**没有执行体** ⇒ 一律 ``400`` 并写明,不静默降级成别的格式。
        """
        p = principal(request, "read")
        body = await json_or_empty(request)
        fmt = body.get("fmt") or "jsonl"
        if fmt not in MESSAGES_EXPORT_FMTS:
            raise ApiError(400, "INVALID_ARGS", f"fmt 须为 {'|'.join(MESSAGES_EXPORT_FMTS)}", reason="bad_fmt",
                           extra={"details": [{"pointer": "/fmt"}]})
        if fmt not in MESSAGES_EXPORT_IMPLEMENTED:
            raise ApiError(400, "INVALID_ARGS", f"fmt='{fmt}' 本期未实现(可用:{'|'.join(MESSAGES_EXPORT_IMPLEMENTED)})",
                           reason="fmt_not_implemented", extra={"details": [{"pointer": "/fmt"}]})
        with_media = body.get("with_media") or "none"
        if with_media not in ("none", "zip"):
            raise ApiError(400, "INVALID_ARGS", "with_media 须为 none|zip", reason="bad_with_media",
                           extra={"details": [{"pointer": "/with_media"}]})
        if with_media == "zip":
            raise ApiError(400, "INVALID_ARGS", "with_media='zip' 本期未实现(媒体打包执行体缺)",
                           reason="with_media_not_implemented", extra={"details": [{"pointer": "/with_media"}]})
        flt = body.get("filter") or {}
        if not isinstance(flt, dict):
            raise ApiError(400, "INVALID_ARGS", "filter 须为对象", reason="bad_filter",
                           extra={"details": [{"pointer": "/filter"}]})
        aid = flt.get("account_id")
        if isinstance(aid, str):
            require_account(p, aid)
        job_id = agent.store.job_create(kind="messages_export", actor=p.actor, account_id=aid if isinstance(aid, str) else None,
                                        params={"fmt": fmt, "with_media": with_media, "filter": flt})

        async def job_body() -> dict[str, Any]:
            rows: list[dict[str, Any]] = []
            before = None
            while True:
                page, _slow = await asyncio.to_thread(
                    lambda: agent.store.query_messages(
                        account_id=flt.get("account_id"), session_id=flt.get("session_id"), dir=flt.get("dir"),
                        type=flt.get("type"), state=flt.get("state"), sender=flt.get("sender"), q=flt.get("q"),
                        since_ms=flt.get("since_ms"), until_ms=flt.get("until_ms"), limit=EXPORT_PAGE, before=before))
                page = [r for r in page if p.allows_account(r["account_id"])]
                rows += page
                if len(page) < EXPORT_PAGE:
                    break
                before = (page[-1]["ts_ms"], page[-1]["id"])
            out_path = os.path.join(agent.data_dir, "exports", f"messages-{job_id}.{fmt}")
            return await asyncio.to_thread(_export_write, job_id, fmt, rows, out_path)

        agent.spawn_job(job_id, "messages_export", job_body)
        _audit(p, "messages.export", detail={"job_id": job_id, "fmt": fmt})
        return JSONResponse(status_code=202, content={"ok": True, "job_id": job_id})
